### ISSUE TITLE
在不同的机器上执行zeroconf的Browse方法有时可以获得dns信息有时不行

### ISSUE THREAD

**Issue by zhou-yong-long** [libp2p/zeroconf#26]
经过debug我发现是在https://github.com/libp2p/zeroconf的Browse方法中无法获取到dns信息，一直debug到这一层
package zeroconf 中 client.go的169-175行代码
```
msgCh := make(chan *dns.Msg, 32)
if c.ipv4conn != nil {
   go c.recv(ctx, c.ipv4conn, msgCh)
}
if c.ipv6conn != nil {
   go c.recv(ctx, c.ipv6conn, msgCh)
}
```
msgCh中没有信息返回，请问是什么问题吗？配置信息都检查过没有出错

**Comment by marten-seemann** [comment]
Sorry, I don't speak Chinese. Please post issues in English.
