### ISSUE TITLE
Browse and Register do not work past localhost on Windows 10/11

### ISSUE THREAD

**Issue by cpuchip** [libp2p/zeroconf#28]
After reading a lot between grandcat's and libp2p's implementation of zeroconf being able to browse zeroconf based services on the local network is completely unreliable on windows, probably due to implementations not being flushed out completely on the windows Golang network stack.

referencing this closed issue: https://github.com/libp2p/zeroconf/issues/24

I wanted to open a ticket here and then later submit a PR that may work well in fixing some of the dire issues with windows, without breaking the other OSes.

I'm going to be referencing [davidflowerday](https://github.com/davidflowerday) work here https://github.com/grandcat/zeroconf/pull/81

I've had great success implementing his SetMulticastInterface calls on client.go and server.go but another user in mentioned here https://github.com/grandcat/zeroconf/issues/69
that replacing UDP connection function net.ListenUDP() to net.ListenMulticastUDP() with a specific interface works, I wanted to try that approach too before putting together a PR.

**Comment by cpuchip** [comment]
See PR for possible fix
https://github.com/libp2p/zeroconf/pull/29

**Comment by brucealthompson** [comment]
I just tested this using both https://github.com/grandcat/zeroconf/blob/master/examples/register/server.go and my modified version that picks a specific local interface @
[main.txt](https://github.com/libp2p/zeroconf/files/14156919/main.txt)
It has the same problem as mention above on Windows.
Please reopen this issue.
I will try the workaround mentioned above and see if that works.
